version: 2
jobs:
  deploy:
    docker:
      - image: clue/httpie
    environment:

    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            cat importmap.json

            echo "Updating import map"
            http PATCH $DEPLOYER_HOST/import-map.json\?env=$DEPLOYER_ENV -a $DEPLOYER_USERNAME:$DEPLOYER_PASSWORD --check-status < importmap.json

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          context: deploy-context
          filters:
            branches:
              only: master
